os: osx
language: c
compiler:
  - clang
  - gcc
addons:
  homebrew:
    packages:
    - openssl
before_install:
  - export PATH="/usr/local/opt/openssl/bin:$PATH"
  - export LDFLAGS="$LDFLAGS -L/usr/local/opt/openssl/lib"
  - export CPPFLAGS="$CPPFLAGS -I/usr/local/opt/openssl/include"
script:
  - make